name: StrategyManager
description: eigen
networks:
- id: 1
  start_block: 0
  contracts:
  - name: StrategyManager
    handler: src/EventHandlers.ts
    address:
    - 0x858646372cc42e1a627fce94aa7a7033e7cf075a
    events:
    - event: Deposit(address depositor, address token, address strategy, uint256 shares)
      requiredEntities:
      - name: EventsSummary
    - event: Initialized(uint8 version)
      requiredEntities:
      - name: EventsSummary
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      requiredEntities:
      - name: EventsSummary
    - event: Paused(address indexed account, uint256 newPausedStatus)
      requiredEntities:
      - name: EventsSummary
    - event: PauserRegistrySet(address pauserRegistry, address newPauserRegistry)
      requiredEntities:
      - name: EventsSummary
    - event: ShareWithdrawalQueued(address depositor, uint96 nonce, address strategy, uint256 shares)
      requiredEntities:
      - name: EventsSummary
    - event: StrategyAddedToDepositWhitelist(address strategy)
      requiredEntities:
      - name: EventsSummary
    - event: StrategyRemovedFromDepositWhitelist(address strategy)
      requiredEntities:
      - name: EventsSummary
    - event: StrategyWhitelisterChanged(address previousAddress, address newAddress)
      requiredEntities:
      - name: EventsSummary
    - event: Unpaused(address indexed account, uint256 newPausedStatus)
      requiredEntities:
      - name: EventsSummary
    - event: WithdrawalCompleted(address indexed depositor, uint96 nonce, address indexed withdrawer, bytes32 withdrawalRoot)
      requiredEntities:
      - name: EventsSummary
    - event: WithdrawalDelayBlocksSet(uint256 previousValue, uint256 newValue)
      requiredEntities:
      - name: EventsSummary
    - event: WithdrawalQueued(address depositor, uint96 nonce, address withdrawer, address delegatedAddress, bytes32 withdrawalRoot)
      requiredEntities:
      - name: EventsSummary
